project:
  type: website
  preview: 
    port: 7777

website:
  title: "R4Analytics"
  favicon: images/logo_site.png
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - icon: github
        href: https://github.com/ubogoeva/R4Analytics

format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: visual

