project:
  type: website
  preview: 
    port: 7777

website:
  title: "R4Analytics"
  favicon: images/logo_site.png
  site-url: https://ubogoeva.github.io/R4Analytics/

  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      # - icon: github
      - icon: rss
        href: https://github.com/ubogoeva/R4Analytics

format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    include-before-body: YMetrics/metrics.js
comments: 
    utterances:
      repo: ubogoeva/R4Analytics_comments
editor: visual

