---
title: "Как добавить яндекс-метрику на сайт Quarto"
author: "Elena U"
date: '16 Apr 2024'
format: html 
editor: visual
theme: yeti
#toc: true
#toc-expand: 2
#toc-depth: 2
code-fold: true
categories: analytics
---

Всем привет!

В какой-то момент мне стало интересно, как работает яндекс-метрика для веб-аналитики, и я решила попробовать это сделать на своем сайте со статьями по R.

Пошаговая инструкция:

1.  Для начала нужно создать счетчик на [сайте](https://metrika.yandex.ru/list) метрики, вписать туда URL сайта, принять условия соглашения и тп.

    Появится уникальный номер счетчика и код счетчика в JavaScript, который нужно добавить на сайт в пределах тегов \<head\>\</head\> или \<body\>\</body\>. Как это сделать в Quarto-сайте не было написано, но все оказалось очень просто и изящно.

2.  Нужно сохранить вышеприведенный код счетчика в файл `.js` в директории проекта сайта например с названием `metrics.js`.

3.  В файле `_quarto.yml`, где хранятся основные настройки сайта вписать:

    ``` yaml
    format:
      html:
        include-before-body: <path_to_file/metrics.js>
    ```

4.  Проверить, что счетчик установлен на странице метрики, если все сделано правильно, то по ссылке появится всплывающее окно о том, что счетчик активен.

5.  Анализировать аналитику сайта.

::: callout-note
## Google-analytics

Google-аналитику можно было прикрепить на сайт относительно [нативным образом](https://quarto.org/docs/websites/website-tools.html#google-analytics), встроенным в Quarto.
:::
